version: '3'
services:
    db:
        container_name: 4for-store-db
        image: mariadb:latest
        environment:
            MARIADB_ROOT_PASSWORD: 'root'
            MARIADB_DATABASE: 'store'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
    php:
        container_name: 4for-store-php
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        volumes:
            - ./src:/var/www/html
        depends_on:
          - db
    web:
        container_name: 4for-store-web
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        expose:
            - "80"
        volumes:
            - ./src:/var/www/html
        depends_on:
          - php
          - db
volumes:
    mysqldata: {}
